apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-deploy
  labels:
      name: employee-app-deploy
      app: demo-employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: employee-app-pod
      app: demo-employee-app
  template:
    metadata:
      name: employee-app-pod
      labels:
        name: employee-app-pod
        app: demo-employee-app  
    spec:
      containers:
      - name: employee-app
        image: amipatel06/springboot-docker-k8s:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
