  
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    name: employee-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: employee-app-pod
    app: demo-employee-app